### ISSUE TITLE
Shopping Cart

### ISSUE THREAD

**Issue by karetiman23** [cs130-w21/Discussion_Test#1]
## Epic
Description and User Benefit:
The shopping cart is a feature that acts much like a real shopping cart in a physical store. It allows the user to store and view items they are interested in purchasing. This will allow the user to buy all their items together at once, rather than having to be each item individually.

User Actions:
- The user should be able to view the items in their shopping cart. This can be done by clicking on a shopping cart icon in the UI.
- The user should be able to add items to the shopping cart. This can be done by clicking the "Add to Shopping Cart" button on any item in the store you have queried.

## User Stories
- [x] View Shopping Cart #2 
- [ ] Add Shopping Cart #3 
- [ ] Add a database: We need this database to organize all the materials. #4
